services:
  planner:
    image: nginx:alpine
    container_name: planner
    # ports:
    #   - "3500:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Optional
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.planner-secure.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.planner-secure.entrypoints=websecure"
      - "traefik.http.routers.planner-secure.tls=true"
      - "traefik.http.routers.planner-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.planner-secure.middlewares=planner-auth"
      - "traefik.http.services.planner.loadbalancer.server.port=80"

      # HTTP router redirects to HTTPS
      - "traefik.http.routers.planner.entrypoints=web"
      - "traefik.http.routers.planner.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.planner.middlewares=https-redirect"

      # Define the middleware here, attached to this service
      - "traefik.http.middlewares.planner-auth.basicauth.users=${SHOPPING_BASIC_AUTH_USERS}"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
