services:
  vite-app:
    image: nginx:alpine
    container_name: planner
    expose:
      - "3500"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vite.rule=Host(`planner.ryan-jasinski.com`)"
      - "traefik.http.services.vite.loadbalancer.server.port=3500"
      - "traefik.http.routers.vite.entrypoints=websecure"
      - "traefik.http.routers.vite.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=neo:$$apr1$$J8qzvc15$$oZVUAdtOkhL1Fjtr51Ni1."
    networks:
      - web

networks:
  web:
    external: true
