services:
  vite-app:
    image: nginx:alpine
    container_name: shopping-list
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vite.rule=Host(`planner.ryan-jasinski.com`)"
      - "traefik.http.routers.vite.entrypoints=web" # or websecure
      - "traefik.http.services.vite.loadbalancer.server.port=80"
      - "traefik.http.routers.vite.rule=Host(`vite.example.com`)"
      - "traefik.http.routers.vite.entrypoints=websecure"
      - "traefik.http.routers.vite.tls.certresolver=letsencrypt"
    networks:
      - web

networks:
  web:
    external: true
